### PR TITLE
Classify rewrite

### PR DESCRIPTION
**Pull request by TobiTenno**
simplify correlation and structure, make everything less bound into the main single file

### CODE REVIEW

**Comment by TobiTenno** [comment]
@filipedeschamps I did a bit more full rewriting and configuring, moved it from a babelified project to a straight node module-based one

if we don't get this moving, i'm gonna re-publish with lots of credit to you.

**Comment by filipedeschamps** [comment]
@TobiTenno great! Working on it and I want to give a lot of credits to you in the readme 👍

**Comment by filipedeschamps** [comment]
Hmmmm this is why Travis is failing to build... all tests passed but this coverage:

image

image

Maybe it's a good idea to fix this before I bump the version on NPM. What do you think? And also, please check the README, I mentioned you twice :)

**Comment by TobiTenno** [comment]
@filipedeschamps you're awesome. I dunno why it's bein odd on it, but i'm happy to take a look at why it's wigging out. I wasn't seeing the travis status on the pr, my bad.

**Pull request merged**
