### PR TITLE
feat(types): add types

### LINKED ISSUE #186: Support typescript for this fantastic library
Hi,
Thanks a lot for this fantastic library. My only request is can you support typescript for this? There exists a ts version [here](https://www.npmjs.com/package/rss-emitter-ts), but it is not in sync with the library here. So we often miss out on the new features. A built-in ts support will be perfect for this. If you need, I can also try and help for this. Hope you agree on getting this done. 😄

### PR DESCRIPTION
**Pull request by TobiTenno**
closes #186

### CODE REVIEW

**Comment by TobiTenno** [comment]
yo, @abdatta could you take a look and make sure this is what you need?

**Comment by abdatta** [comment]
Hey okay, I'll take a look and let you know by tomorrow.

**Comment by TobiTenno** [comment]
@abdatta i got it figured out. turns out `tsc` that we tried to use in our build script with npx is an old deprecated copy of typescript, so we need to specify `npx -p typescript tsc -p tsconfig.declaration.json`

**Comment by TobiTenno** [comment]
@filipedeschamps if you could review real fast, this makes the lib usable on typescript-based projects a lot easier

**Comment by TobiTenno** [comment]
@filipedeschamps whenever you approve this, i can get it merged

**Comment by TobiTenno** [comment]
@abdatta if you copy my branch and put a PR in, i can approve and merge it, i just can't approve & merge them if i submit the pr

**Pull request merged**
