### PR TITLE
fix: re-add nyc wrapper

### PR DESCRIPTION
**Pull request by TobiTenno**
I re-added the nyc wrapping call, which fixes the coverage step (on my travis build, at least)

https://travis-ci.com/TobiTenno/rss-feed-emitter/builds/144546100

### CODE REVIEW

**Comment by filipedeschamps** [comment]
You're awesome 😍

**Comment by filipedeschamps** [comment]
Maybe npx is causing this?

image

**Comment by TobiTenno** [comment]
I think that just means it's not configured on coveralls.io

**Comment by filipedeschamps** [comment]
Yeah, somehow it really was disabled, don't know why. Reenabling it worked just fine 👍

**Pull request merged**
