### PR TITLE
chore(ci): support auto-releasing with semantic-release

### PR DESCRIPTION
**Pull request by TobiTenno**

### CODE REVIEW

**Comment by TobiTenno** [comment]
ah, looks like you added branch. problem is that since it's on my fork, that one won't exist.

**Comment by TobiTenno** [comment]
we might wanna remove the `Travis CI - Branch` build, cause that only works properly if the build started from a branch on this repo, @filipedeschamps

**Comment by filipedeschamps** [comment]
Done! But looks like the `Travis CI - Branch Expected — Waiting for status to be reported` is still stuck, even if I trig a rebuild. Maybe you need to push it again 👍 

image

**Comment by filipedeschamps** [comment]
I gave you the wrong information, looks like everything is going to work now 👍

**Comment by TobiTenno** [comment]
@filipedeschamps did you add the GH token as well?

**Comment by TobiTenno** [comment]
I canceled the current job because it'll fail if there's no `GITHUB_TOKEN` with a personal access token so it can make the github release & tag & comment on the pr's

**Comment by filipedeschamps** [comment]
Do you know if I can create a personal token to just one repository?  Anyway, probably I just need to enable `repo > public_repo` right?

image

**Comment by TobiTenno** [comment]
That seems right from what I'm reading

**Comment by TobiTenno** [comment]
And no, I don't know of a way for it to be limited to the one repo, but no one but the ci job will be able to release using it, so it's not like it can go haywire easily

**Comment by filipedeschamps** [comment]
Done 👍 

image

**Comment by filipedeschamps** [comment]
Also, we need to add you into the NPM page, it's not fair that I'm the only one listed 👍 

image

**Comment by TobiTenno** [comment]
feel free, i don't remember exactly how.

**Comment by TobiTenno** [comment]
```
npm ERR! code EOTP
npm ERR! This operation requires a one-time password from your authenticator.
npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.
npm ERR! If you already provided a one-time password then it is likely that you either typoed
npm ERR! it, or it timed out. Please try again.
```

looks like the code you provided needs to include bypassing OTP, or you have to turn it off, unsure which you want to do.

**Comment by filipedeschamps** [comment]
Yep, I changed from `Authorization and Publishing` to `Authorization`, recreated the token and added it to Travis CI 👍

**Comment by filipedeschamps** [comment]
@TobiTenno that's neat 👍

**Pull request merged**
