### PR TITLE
Fix vulnerabilities

### PR DESCRIPTION
**Pull request by TobiTenno**
- Uplift project to work on newer versions of nodejs
- Remove vulnerabilities due to dependent versions of lodash and many other dependencies
- Update testing & coverage scripts

Sadly, some of the integrations don't work and a couple of the unit tests don't work, however the actual functionality of the lib is still there.

### CODE REVIEW

**Comment by TobiTenno** [comment]
can we please get rid of these checks that are bloating it, considering these have nested functions that only got moved around, and these "checks" are completely useless, seeing as all they do is prompt more global methods...

**Comment by filipedeschamps** [comment]
I will just give me a little more time to review your PR. And by the way, thank you for everything already 👍

**Comment by TobiTenno** [comment]
@filipedeschamps how's it going?

**Comment by TobiTenno** [comment]
@filipedeschamps any progress?

**Pull request closed without merging**
