### PR TITLE
feat: implement array urls

### LINKED ISSUE #156: Implement use of url array
Instead of doing one add per url like this
```
feeder.add({ url: 'http://lorem-rss.herokuapp.com/feed' });
feeder.add({ url: 'http://lorem-rss.herokuapp.com/feed?unit=second&interval=30' });
```
can you implement that we add a array of url's ?
```
feeder.add({ url: {
 'http://lorem-rss.herokuapp.com/feed',
 'http://lorem-rss.herokuapp.com/feed?unit=second&interval=30'
});
```

### LINKED ISSUE #163: Specify the event name which Event emitter calls when adding a feed
Thanks for the handy library!

This is a feature request.
When adding multiple feeds...
```js
feeder.add({
    url: url1,
    refresh: 6000,
})

feeder.add({
    url: url2,
    refresh: 6000,
})

feeder.on('new-item', function(item) {
    if (item.url.includes(url1)) methodA()
    else if (item.url.includes(url2)) methodB()
}
```
It's a bit troublesome when we want to handle for each feed.

```js
feeder.add({
    url: url1,
    refresh: 6000,
    eventName: 'new-item-url1',
})

feeder.add({
    url: url2,
    refresh: 6000,
    eventName: 'new-item-url2',
})

feeder.on('new-item-url1', function(item) {
}

feeder.on('new-item-url2', function(item) {
}
```
This is more simple.

Would you implement this feature?
Thanks!

### LINKED ISSUE #164: Distribute ES6 too?
Node 8 and 9 should work with your ES6 too, so why not publish this version too aside to ES5 version?

### LINKED ISSUE #170: Event for once the initial load is completed
It would be helpful to have an event once the initial load of all the rss feeds are completed. For example, some people might not want to do anything with the items already existing in the feeds, and could do something like this:

```
feeder.on('initial-load', function () {
    console.log('Waiting for something new!')
    feeder.on('new-item', function (item) {
        doSomething(item)
    })
})
```

### LINKED ISSUE #171: how can i make it to show only today feeds, than old feeds?
right now, all the feeds are showing, I don't wanna pull feeds from old date. is there any syntax to show current feeds.

### PR DESCRIPTION
**Pull request by TobiTenno**
closes #156
closes #163 
closes #164 (done a while ago, but marking here to make it close automagically)
closes #170 
closes #171 
work back towards 100% coverage
fix issues with integration specs
support adding multiple feeds at once in a few different ways...
```js
const Feeder = require('rss-feed-emitter');

const feeder = new Feeder();
feeder.add({
  url: ['https://github.com', 'https://npmjs.org'],
}, {
  url: 'https://microsoft.com'
});
```

### CODE REVIEW

**Comment by filipedeschamps** [comment]
For some reason, I think nock's breaking change is breaking some tests.

**Comment by TobiTenno** [comment]
yeah, found that when i checked it against the old version. latest changes reverts it

**Comment by TobiTenno** [comment]
(and gets regression specs working again)

**Comment by TobiTenno** [comment]
this lowered my coverage a bit, i'll see if i can figure out what i'm missing in the logic and add another spec to cover it. if you have any thought what i'm missing, let me know.

**Comment by TobiTenno** [comment]
looks inconsistent on when that one failed... could you re-trigger the build? (also, you may want to consider moving it to travis-ci.com so you can get the more updated checks api  integration)

**Comment by filipedeschamps** [comment]
I think it got the same results, very strange. It's always `1) should always keep feed max history the number of feed items times 3`.

Anyway, you are doing such a great job in this repository that I'm giving you write permission 👍 🤝

**Comment by TobiTenno** [comment]
@filipedeschamps wanted to get your thoughts on doing automated releases with [semantic release](https://github.com/semantic-release/semantic-release), if that'd be ok with you. it's relatively easy to adopt, and it'll decrease the amount of decision making about when to do releases that we'd have to do.

**Comment by filipedeschamps** [comment]
I never used this kind of workflow but seems awesome! Especially now with Github Actions, we can publish it directly to npm 👍

**Comment by TobiTenno** [comment]
I was going to do it through Travis, since the workflow for almost all of it is already there, just need to add the release step

**Comment by filipedeschamps** [comment]
Makes total sense 👍 🤝

**Comment by TobiTenno** [comment]
I'm not able to turn the project on on travis-ci.com, could you turn it on there, and then add an environment variable called "NPM_TOKEN" and make it only available to the master branch? 

It should look like this when you're done: 
image

I'm not able to turn it on with my access level. 

Once that's done, I'd be happy to merge this and do another PR to set up the release process.

**Comment by TobiTenno** [comment]
I'm gonna go ahead and merge this and we'll figure out automated releases later

**Comment by filipedeschamps** [comment]
@TobiTenno NPM_TOKEN added to https://travis-ci.org/github/filipedeschamps/rss-feed-emitter and only to `master` branch 👍

**Comment by TobiTenno** [comment]
could you move it to travis-ci.com to be more in line with travis' go-forward plans for open source projects?

**Comment by filipedeschamps** [comment]
Oh, I didn't know about this, thanks for point it out! 😍   I've used travis-ci.com tool to migrate the travis-ci.org repository and looks like it worked. Let me double check 👍

**Comment by filipedeschamps** [comment]
Yep!

image

**Comment by TobiTenno** [comment]
awesome! I'll put a pr in momentarily for auto releasing

**Pull request merged**
